name: smart_event_planner
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  # State management.
  flutter_bloc: ^9.0.0
  # Code generator (mainly used with cubit & retrofit).
  freezed: ^2.5.8
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  freezed_annotation: ^2.4.4
  # for dependency injection
  get_it: ^8.0.3
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.9.3
  # Annotations for the json_serializable code-generator.
  json_annotation: ^4.9.0
  # --Networking--
  # -A powerful HTTP networking package, supports Interceptors, Aborting and canceling a request, Custom adapters, Transformers, etc.
  dio: ^5.7.0
  # -A dio client generator.
  retrofit: ^4.4.2
  # -A code generator for the retrofit client.
  retrofit_generator: ^9.1.7
  # -A Dio interceptor that logs network calls in a pretty, easy to read format.
  pretty_dio_logger: ^1.4.0
  # -Discovering the state of the network.
  connectivity_plus: ^6.1.2
  # --Localization--
  intl: ^0.19.0
  easy_localization: ^3.0.7+1
  # Customize Flutter's default white native splash screen
  flutter_native_splash: ^2.4.4
  # Cache network images. Can also be used with placeholder and error widgets.
  cached_network_image: ^3.4.1
  # For custom icons
  iconsax: ^0.0.8
  # Converts already built widgets into skeleton loaders with no extra effort.
  skeletonizer: ^1.4.3
  # Render After Effects animations natively on Flutter.
  lottie: ^3.3.1
  # A carousel slider widget, support infinite scroll and custom child widget.
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  # Selecting images from the Android and iOS image library
  image_picker: ^1.1.2
  dartz: ^0.10.1
  device_preview: ^1.2.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/user/
    - assets/images/animations/
    - assets/images/events/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 800
          style: italic
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon/appLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter_intl:
  enabled: true
