// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAj-woeoZTwZn7cZ0m9n_Lfb7Xtg9qIWDU',
    appId: '1:1037520455352:web:d1697ac9ee1ca5576d564d',
    messagingSenderId: '1037520455352',
    projectId: 'smart-event-c25bf',
    authDomain: 'smart-event-c25bf.firebaseapp.com',
    storageBucket: 'smart-event-c25bf.firebasestorage.app',
    measurementId: 'G-PW1ZGGK2TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoLJtfW5fUmN0OEemAOuVLunb5zkMth7Y',
    appId: '1:1037520455352:android:2a751cbc4b782c726d564d',
    messagingSenderId: '1037520455352',
    projectId: 'smart-event-c25bf',
    storageBucket: 'smart-event-c25bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCA5rr4SCPOxDKo9Y5-k1_RNJ0X9rxahY',
    appId: '1:1037520455352:ios:2469576d18c00c086d564d',
    messagingSenderId: '1037520455352',
    projectId: 'smart-event-c25bf',
    storageBucket: 'smart-event-c25bf.firebasestorage.app',
    iosBundleId: 'com.example.smartEventPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCA5rr4SCPOxDKo9Y5-k1_RNJ0X9rxahY',
    appId: '1:1037520455352:ios:2469576d18c00c086d564d',
    messagingSenderId: '1037520455352',
    projectId: 'smart-event-c25bf',
    storageBucket: 'smart-event-c25bf.firebasestorage.app',
    iosBundleId: 'com.example.smartEventPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAj-woeoZTwZn7cZ0m9n_Lfb7Xtg9qIWDU',
    appId: '1:1037520455352:web:be02000d873ae6906d564d',
    messagingSenderId: '1037520455352',
    projectId: 'smart-event-c25bf',
    authDomain: 'smart-event-c25bf.firebaseapp.com',
    storageBucket: 'smart-event-c25bf.firebasestorage.app',
    measurementId: 'G-FX3RW7HKL7',
  );
}
