// import 'package:dio/dio.dart';
// import 'package:flutter/widgets.dart';

// class TestApi {
//   final String baseUrl =
//       "https://eventplanner-production-ce6e.up.railway.app/api/events/";
//   final String baseUrl2 =
//       "https://eventplanner-production-ce6e.up.railway.app/";

//   final String event = "getevents";

//   final String accessToken =
//       'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2UxZjUyNmE5Y2VjYjVkNmJhZDlhMTQiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3NDI4NjQ3MzMsImV4cCI6MTc0Mjg2ODMzM30.kOGqSPuo2wSVVrwIKu5BcQ5ijOtrqEHVCn2UGMeXzrc';
//   final String chat = 'chat';

//   Dio _dio = Dio();

//   Future<Map<String, dynamic>> getEvents() async {
//     final response = await _dio.get(
//       baseUrl + event,
//       options: Options(headers: {'Authorization': 'Bearer $accessToken'}),
//     );

//     debugPrint('Response: ${response.data}');

//     return response.data;
//   }

//   int c = 0;

//   Future<dynamic> chattest({required String message}) async {
//     try {
//       final response = await _dio.post(
//         data: {
//           "message": message,
//         },
//         baseUrl2 + chat,
//         options: Options(
//             //contentType: 'application/json',
//             //headers: {'Authorization': 'Bearer $accessToken'},
//             ),
//       );

//       debugPrint((c++).toString());
//       debugPrint('Response: ${response.data['response'][0]}');

//       return response.data['response'][0];
//     } on Exception catch (e) {
//       throw Exception(e);
//     }
//   }
// }

// class Autogenerated {
//   String? sId;
//   String? name;
//   String? description;
//   String? category;
//   Location? location;
//   String? status;
//   String? hostCompany;
//   String? isRecurring;
//   String? date;
//   String? time;
//   String? price;
//   String? type;
//   bool? paid;
//   String? host;
//   List<Null>? attendees;
//   int? iV;

//   Autogenerated({
//     this.sId,
//     this.name,
//     this.description,
//     this.category,
//     this.location,
//     this.status,
//     this.hostCompany,
//     this.isRecurring,
//     this.date,
//     this.time,
//     this.price,
//     this.type,
//     this.paid,
//     this.host,
//     this.attendees,
//     this.iV,
//   });

//   Autogenerated.fromJson(Map<String, dynamic> json) {
//     sId = json['_id'];
//     name = json['name'];
//     description = json['description'];
//     category = json['category'];
//     location = json['location'] != null
//         ? new Location.fromJson(json['location'])
//         : null;
//     status = json['status'];
//     hostCompany = json['hostCompany'];
//     isRecurring = json['isRecurring'];
//     date = json['date'];
//     time = json['time'];
//     price = json['price'];
//     type = json['type'];
//     paid = json['paid'];
//     host = json['host'];

//     iV = json['__v'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['_id'] = this.sId;
//     data['name'] = this.name;
//     data['description'] = this.description;
//     data['category'] = this.category;
//     if (this.location != null) {
//       data['location'] = this.location!.toJson();
//     }
//     data['status'] = this.status;
//     data['hostCompany'] = this.hostCompany;
//     data['isRecurring'] = this.isRecurring;
//     data['date'] = this.date;
//     data['time'] = this.time;
//     data['price'] = this.price;
//     data['type'] = this.type;
//     data['paid'] = this.paid;
//     data['host'] = this.host;
//     // data['attendees'] = [];
//     data['__v'] = this.iV;
//     return data;
//   }
// }

// class Location {
//   String? address;
//   double? latitude;
//   double? longitude;

//   Location({this.address, this.latitude, this.longitude});

//   Location.fromJson(Map<String, dynamic> json) {
//     address = json['address'];
//     latitude = json['latitude'];
//     longitude = json['longitude'];
//   }

//   Map<String, dynamic> toJson() {
//     final Map<String, dynamic> data = new Map<String, dynamic>();
//     data['address'] = this.address;
//     data['latitude'] = this.latitude;
//     data['longitude'] = this.longitude;
//     return data;
//   }
// }
